import type { Metadata } from "next"
import localfont from "next/font/local"
import "./globals.css"
import LenisProvider from "@/components/LenisProvider"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"

const myFont = localfont({ src: "../../public/fonts/benzo.ttf" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} antialiased`}>
        <LenisProvider>
          <Navbar/>
          {children}
          <Footer/>
        </LenisProvider>
      </body>
    </html>
  )
}
